# Generated by Django 2.0 on 2020-03-19 08:18

from django.db import migrations, models
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
